# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.ssh.insert_key = false
    config.vm.define "lb" do |lb|
        lb.vm.box = "centos/7"
        lb.vm.hostname = "lb"
        lb.vm.network "private_network", ip: "192.168.1.200"
        lb.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1", "--name", "lb"]
        end
        
        lb.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/haproxy/loadbalancer.yml"
            ansible.extra_vars= {
                "web_servers" => [
                    {"name": "web-1", "ip": "192.168.1.6"},
                    {"name": "web-2", "ip": "192.168.1.7"}
                ]
            }
            end
        end
    
        (1..2).each do |i|
            config.vm.define "web-#{i}" do |web|
                web.vm.box = "centos/7"
                web.vm.network "private_network", ip: "192.168.1.6#{i}" 
                web.vm.hostname = "web-#{i}"
                web.vm.provider "virtualbox" do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1", "--name", "web-#{i}"]
                end
                web.vm.provision "ansible" do |ansible|
                    ansible.playbook = "playbooks/haproxy/loa"
                    ansible.groups = {
                        "servers" => ["Web-#{i}"]
                    }
                end
            end
        end
        
        config.vm.define "db" do |db|
            db.vm.box = "centos/7"
            db.vm.hostname = "db"
            db.vm.network "private_network", ip: "192.168.1.100"
            db.vm.provision "shell", inline: "echo DB Server"
        end
    end